using System.Collections.Generic;

namespace Main {
   public static class TypeInfo {
      // one to ones are not included
      public readonly static Dictionary<string /*c type*/, string /*csharp equivalent*/> basicTypes = new Dictionary<string, string>() {
         { "bool", "byte" },
         { "_Bool", "byte" },
         { "unsigned char", "byte" },
         { "signed char", "sbyte" }, // signed specifier can be ignored other than "signed char"
         { "char", "byte" },
         { "size_t", "uint" },
         { "unsigned int", "uint" },
         { "unsigned short", "ushort" },
         { "unsigned short int", "ushort" },
         { "unsigned long", "ulong" },
         { "unsigned long int", "ulong" },
         { "unsigned long long", "ulong" },
         { "unsigned long long int", "ulong" },
         { "short int", "short" },
         { "long int", "long" },
         { "long long int", "long" },
         { "long unsigned int", "uint" },
         { "long double", "double" },
      };

      public readonly static HashSet<string> allowedFixedSizeBufferTypes = new HashSet<string>() {
         // Fixed size buffer type must be one of the following: bool, byte, short, int, long, char, sbyte, ushort, uint, ulong, float or double [Main]csharp(CS1663)
         "bool",
         "byte",
         "short",
         "int",
         "long",
         "char",
         "sbyte",
         "ushort",
         "uint",
         "ulong",
         "float",
         "double",
      };

      // used to check if member type of a struct is known. If it is one of these types then it is okay.
      // This set doesnt necessarily need to include all the types but it needs to include all the ones that are generated by ctocs
      public readonly static HashSet<string> builtinCSharpTypes = new HashSet<string>() {
         "bool",
         "byte",
         "sbyte",
         "short",
         "ushort",
         "int",
         "uint",
         "long",
         "ulong",
         "float",
         "double",
         "char",
         "string",
         "object",
         "decimal",
         "void",
      };
   }
}
