/**
 *   This file is auto generated by ctocs (c to cs)
 *   https://github.com/apilatosba/ctocs
**/
using System;
using System.Runtime.InteropServices;
using static stb_image.Native;

namespace stb_image {
	// DELEGATES
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate int stbi_io_callbacks_read_DELEGATE(void* user, byte* data, int size);
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate void stbi_io_callbacks_skip_DELEGATE(void* user, int n);
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate int stbi_io_callbacks_eof_DELEGATE(void* user);
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate int __compar_fn_t(void* __ANONYMOUS__PARAMETER_0, void* __ANONYMOUS__PARAMETER_1);

	public static unsafe partial class Native {
		public const string LIBRARY_NAME = @"stb_image.so";

		// DEFINES
		public const int STBI_VERSION = 1;
		public const uint STBI__MARKER_none = 0xff;
		public const int STBI__HDR_BUFLEN = 1024;

		// DEFINES THAT ARE WRITTEN IN TERMS OF OTHER DEFINES

		// GLOBAL CONST VARIABLES

		// ENUMS (extracted out)

		// ANONYMOUS ENUMS
		public const int STBI_default = 0;
		public const int STBI_grey = 1;
		public const int STBI_grey_alpha = 2;
		public const int STBI_rgb = 3;

		// FUNCTIONS
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_from_memory")]
		public static extern byte* stbi_load_from_memory(byte* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_from_callbacks")]
		public static extern byte* stbi_load_from_callbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load")]
		public static extern byte* stbi_load(byte* filename, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_from_file")]
		public static extern byte* stbi_load_from_file(_IO_FILE* f, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_gif_from_memory")]
		public static extern byte* stbi_load_gif_from_memory(byte* buffer, int len, int** delays, int* x, int* y, int* z, int* comp, int req_comp);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_16_from_memory")]
		public static extern ushort* stbi_load_16_from_memory(byte* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_16_from_callbacks")]
		public static extern ushort* stbi_load_16_from_callbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_16")]
		public static extern ushort* stbi_load_16(byte* filename, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_load_from_file_16")]
		public static extern ushort* stbi_load_from_file_16(_IO_FILE* f, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_loadf_from_memory")]
		public static extern float* stbi_loadf_from_memory(byte* buffer, int len, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_loadf_from_callbacks")]
		public static extern float* stbi_loadf_from_callbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_loadf")]
		public static extern float* stbi_loadf(byte* filename, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_loadf_from_file")]
		public static extern float* stbi_loadf_from_file(_IO_FILE* f, int* x, int* y, int* channels_in_file, int desired_channels);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_hdr_to_ldr_gamma")]
		public static extern void stbi_hdr_to_ldr_gamma(float gamma);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_hdr_to_ldr_scale")]
		public static extern void stbi_hdr_to_ldr_scale(float scale);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_ldr_to_hdr_gamma")]
		public static extern void stbi_ldr_to_hdr_gamma(float gamma);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_ldr_to_hdr_scale")]
		public static extern void stbi_ldr_to_hdr_scale(float scale);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_hdr_from_callbacks")]
		public static extern int stbi_is_hdr_from_callbacks(stbi_io_callbacks* clbk, void* user);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_hdr_from_memory")]
		public static extern int stbi_is_hdr_from_memory(byte* buffer, int len);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_hdr")]
		public static extern int stbi_is_hdr(byte* filename);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_hdr_from_file")]
		public static extern int stbi_is_hdr_from_file(_IO_FILE* f);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_failure_reason")]
		public static extern byte* stbi_failure_reason();
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_image_free")]
		public static extern void stbi_image_free(void* retval_from_stbi_load);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_info_from_memory")]
		public static extern int stbi_info_from_memory(byte* buffer, int len, int* x, int* y, int* comp);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_info_from_callbacks")]
		public static extern int stbi_info_from_callbacks(stbi_io_callbacks* clbk, void* user, int* x, int* y, int* comp);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_16_bit_from_memory")]
		public static extern int stbi_is_16_bit_from_memory(byte* buffer, int len);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_16_bit_from_callbacks")]
		public static extern int stbi_is_16_bit_from_callbacks(stbi_io_callbacks* clbk, void* user);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_info")]
		public static extern int stbi_info(byte* filename, int* x, int* y, int* comp);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_info_from_file")]
		public static extern int stbi_info_from_file(_IO_FILE* f, int* x, int* y, int* comp);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_16_bit")]
		public static extern int stbi_is_16_bit(byte* filename);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_is_16_bit_from_file")]
		public static extern int stbi_is_16_bit_from_file(_IO_FILE* f);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_set_unpremultiply_on_load")]
		public static extern void stbi_set_unpremultiply_on_load(int flag_true_if_should_unpremultiply);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_convert_iphone_png_to_rgb")]
		public static extern void stbi_convert_iphone_png_to_rgb(int flag_true_if_should_convert);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_set_flip_vertically_on_load")]
		public static extern void stbi_set_flip_vertically_on_load(int flag_true_if_should_flip);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_set_unpremultiply_on_load_thread")]
		public static extern void stbi_set_unpremultiply_on_load_thread(int flag_true_if_should_unpremultiply);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_convert_iphone_png_to_rgb_thread")]
		public static extern void stbi_convert_iphone_png_to_rgb_thread(int flag_true_if_should_convert);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_set_flip_vertically_on_load_thread")]
		public static extern void stbi_set_flip_vertically_on_load_thread(int flag_true_if_should_flip);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_malloc_guesssize")]
		public static extern byte* stbi_zlib_decode_malloc_guesssize(byte* buffer, int len, int initial_size, int* outlen);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_malloc_guesssize_headerflag")]
		public static extern byte* stbi_zlib_decode_malloc_guesssize_headerflag(byte* buffer, int len, int initial_size, int* outlen, int parse_header);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_malloc")]
		public static extern byte* stbi_zlib_decode_malloc(byte* buffer, int len, int* outlen);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_buffer")]
		public static extern int stbi_zlib_decode_buffer(byte* obuffer, int olen, byte* ibuffer, int ilen);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_noheader_malloc")]
		public static extern byte* stbi_zlib_decode_noheader_malloc(byte* buffer, int len, int* outlen);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "stbi_zlib_decode_noheader_buffer")]
		public static extern int stbi_zlib_decode_noheader_buffer(byte* obuffer, int olen, byte* ibuffer, int ilen);
	}

	// STRUCTS
	public unsafe partial struct _G_fpos_t {
		public long __pos;
		public __mbstate_t __state;
	}
	public unsafe partial struct _G_fpos64_t {
		public long __pos;
		public __mbstate_t __state;
	}
	public unsafe partial struct _IO_FILE {
		public int _flags;
		public byte* _IO_read_ptr;
		public byte* _IO_read_end;
		public byte* _IO_read_base;
		public byte* _IO_write_base;
		public byte* _IO_write_ptr;
		public byte* _IO_write_end;
		public byte* _IO_buf_base;
		public byte* _IO_buf_end;
		public byte* _IO_save_base;
		public byte* _IO_backup_base;
		public byte* _IO_save_end;
		public _IO_marker* _markers;
		public _IO_FILE* _chain;
		public int _fileno;
		public int _flags2;
		public long _old_offset;
		public ushort _cur_column;
		public sbyte _vtable_offset;
		public fixed byte _shortbuf[(1)];
		public void* _lock;
		public long _offset;
		public _IO_codecvt* _codecvt;
		public _IO_wide_data* _wide_data;
		public _IO_FILE* _freeres_list;
		public void* _freeres_buf;
		public ulong __pad5;
		public int _mode;
		public fixed byte _unused2[(15 * sizeof (int) - 4 * 8 - sizeof (ulong))];
	}
	public unsafe partial struct timeval {
		public long tv_sec;
		public long tv_usec;
	}
	public unsafe partial struct timespec {
		public long tv_sec;
		public long tv_nsec;
	}
	public unsafe partial struct __pthread_internal_list {
		public __pthread_internal_list* __prev;
		public __pthread_internal_list* __next;
	}
	public unsafe partial struct __pthread_internal_slist {
		public __pthread_internal_slist* __next;
	}
	public unsafe partial struct __pthread_mutex_s {
		public int __lock;
		public uint __count;
		public int __owner;
		public uint __nusers;
		public int __kind;
		public short __spins;
		public short __elision;
		public __pthread_internal_list __list;
	}
	public unsafe partial struct __pthread_rwlock_arch_t {
		public uint __readers;
		public uint __writers;
		public uint __wrphase_futex;
		public uint __writers_futex;
		public uint __pad3;
		public uint __pad4;
		public int __cur_writer;
		public int __shared;
		public sbyte __rwelision;
		public __pthread_rwlock_arch_t___pad1_unsignedchar_FIXED_BUFFER __pad1;
		public ulong __pad2;
		public uint __flags;
	}
	public unsafe partial struct random_data {
		public int* fptr;
		public int* rptr;
		public int* state;
		public int rand_type;
		public int rand_deg;
		public int rand_sep;
		public int* end_ptr;
	}
	public unsafe partial struct __fsid_t {
		public fixed int __val[(2)];
	}
	public unsafe partial struct __mbstate_t {
		public int __count;
		public __mbstate_t___value_UNION __value;
	}
	public unsafe partial struct div_t {
		public int quot;
		public int rem;
	}
	public unsafe partial struct ldiv_t {
		public long quot;
		public long rem;
	}
	public unsafe partial struct lldiv_t {
		public long quot;
		public long rem;
	}
	public unsafe partial struct __sigset_t {
		public __sigset_t___val_unsignedlongint_FIXED_BUFFER __val;
	}
	public unsafe partial struct fd_set {
		public fd_set___fds_bits___fd_mask_FIXED_BUFFER __fds_bits;
	}
	public unsafe partial struct __once_flag {
		public int __data;
	}
	public unsafe partial struct stbi_io_callbacks {
		public stbi_io_callbacks_read_DELEGATE read;
		public stbi_io_callbacks_skip_DELEGATE skip;
		public stbi_io_callbacks_eof_DELEGATE eof;
	}
	public unsafe partial struct __atomic_wide_counter___value32_STRUCT {
		public uint __low;
		public uint __high;
	}

	// OPAQUE STRUCTS
	public partial struct _IO_marker { }
	public partial struct _IO_codecvt { }
	public partial struct _IO_wide_data { }

	// UNIONS
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_attr_t {
		[FieldOffset(0)]
		public fixed byte __size[(56)];
		[FieldOffset(0)]
		public long __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_mutexattr_t {
		[FieldOffset(0)]
		public fixed byte __size[(4)];
		[FieldOffset(0)]
		public int __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_condattr_t {
		[FieldOffset(0)]
		public fixed byte __size[(4)];
		[FieldOffset(0)]
		public int __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_mutex_t {
		[FieldOffset(0)]
		public __pthread_mutex_s __data;
		[FieldOffset(0)]
		public fixed byte __size[(40)];
		[FieldOffset(0)]
		public long __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_rwlock_t {
		[FieldOffset(0)]
		public __pthread_rwlock_arch_t __data;
		[FieldOffset(0)]
		public fixed byte __size[(56)];
		[FieldOffset(0)]
		public long __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_rwlockattr_t {
		[FieldOffset(0)]
		public fixed byte __size[(8)];
		[FieldOffset(0)]
		public long __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_barrier_t {
		[FieldOffset(0)]
		public fixed byte __size[(32)];
		[FieldOffset(0)]
		public long __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct pthread_barrierattr_t {
		[FieldOffset(0)]
		public fixed byte __size[(4)];
		[FieldOffset(0)]
		public int __align;
	}
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct __mbstate_t___value_UNION {
		[FieldOffset(0)]
		public uint __wch;
		[FieldOffset(0)]
		public fixed byte __wchb[(4)];
	}

	// OPAQUE UNIONS

	// FIXED BUFFER STRUCTS
	public unsafe partial struct __pthread_rwlock_arch_t___pad1_unsignedchar_FIXED_BUFFER {
		public byte e0;
		public byte e1;
		public byte e2;
		public byte e3;
		public byte e4;
		public byte e5;
		public byte e6;
		public ref byte this[int index] => ref AsSpan()[index];
		public Span<byte> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 7);
	}
	public unsafe partial struct __pthread_cond_s___g_refs_unsignedint_FIXED_BUFFER {
		public uint e0;
		public uint e1;
		public ref uint this[int index] => ref AsSpan()[index];
		public Span<uint> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 2);
	}
	public unsafe partial struct __pthread_cond_s___g_size_unsignedint_FIXED_BUFFER {
		public uint e0;
		public uint e1;
		public ref uint this[int index] => ref AsSpan()[index];
		public Span<uint> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 2);
	}
	public unsafe partial struct __pthread_cond_s___g_signals_unsignedint_FIXED_BUFFER {
		public uint e0;
		public uint e1;
		public ref uint this[int index] => ref AsSpan()[index];
		public Span<uint> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 2);
	}
	public unsafe partial struct drand48_data___x_unsignedshortint_FIXED_BUFFER {
		public ushort e0;
		public ushort e1;
		public ushort e2;
		public ref ushort this[int index] => ref AsSpan()[index];
		public Span<ushort> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 3);
	}
	public unsafe partial struct drand48_data___old_x_unsignedshortint_FIXED_BUFFER {
		public ushort e0;
		public ushort e1;
		public ushort e2;
		public ref ushort this[int index] => ref AsSpan()[index];
		public Span<ushort> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 3);
	}
	public unsafe partial struct __sigset_t___val_unsignedlongint_FIXED_BUFFER {
		public ulong e0;
		public ulong e1;
		public ulong e2;
		public ulong e3;
		public ulong e4;
		public ulong e5;
		public ulong e6;
		public ulong e7;
		public ulong e8;
		public ulong e9;
		public ulong e10;
		public ulong e11;
		public ulong e12;
		public ulong e13;
		public ulong e14;
		public ulong e15;
		public ref ulong this[int index] => ref AsSpan()[index];
		public Span<ulong> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 16);
	}
	public unsafe partial struct fd_set___fds_bits___fd_mask_FIXED_BUFFER {
		public long e0;
		public long e1;
		public long e2;
		public long e3;
		public long e4;
		public long e5;
		public long e6;
		public long e7;
		public long e8;
		public long e9;
		public long e10;
		public long e11;
		public long e12;
		public long e13;
		public long e14;
		public long e15;
		public ref long this[int index] => ref AsSpan()[index];
		public Span<long> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 16);
	}

	// ENUMS

	// OPAQUE ENUMS

	// SAFE WRAPPER
	/**
	 *    The functions here may not always work depending on how the function uses the pointer
	 *    You should know when to use these functions instead of the functions in Native
	**/
	public static unsafe partial class Safe {
		public static byte* stbi_load_from_memory(byte[] buffer, int len, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_from_memory(bufferPtr, len, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static byte* stbi_load_from_callbacks(stbi_io_callbacks* clbk, void* user, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_from_callbacks(clbk, user, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static byte* stbi_load(byte[] filename, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* filenamePtr = &filename[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load(filenamePtr, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static byte* stbi_load_from_file(_IO_FILE* f, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_from_file(f, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static byte* stbi_load_gif_from_memory(byte[] buffer, int len, int** delays, int[] x, int[] y, int[] z, int[] comp, int req_comp) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* zPtr = &z[0])
			fixed(int* compPtr = &comp[0])
				return Native.stbi_load_gif_from_memory(bufferPtr, len, delays, xPtr, yPtr, zPtr, compPtr, req_comp);
		}
		public static ushort* stbi_load_16_from_memory(byte[] buffer, int len, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_16_from_memory(bufferPtr, len, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static ushort* stbi_load_16_from_callbacks(stbi_io_callbacks* clbk, void* user, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_16_from_callbacks(clbk, user, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static ushort* stbi_load_16(byte[] filename, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* filenamePtr = &filename[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_16(filenamePtr, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static ushort* stbi_load_from_file_16(_IO_FILE* f, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_load_from_file_16(f, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static float* stbi_loadf_from_memory(byte[] buffer, int len, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_loadf_from_memory(bufferPtr, len, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static float* stbi_loadf_from_callbacks(stbi_io_callbacks* clbk, void* user, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_loadf_from_callbacks(clbk, user, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static float* stbi_loadf(byte[] filename, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(byte* filenamePtr = &filename[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_loadf(filenamePtr, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static float* stbi_loadf_from_file(_IO_FILE* f, int[] x, int[] y, int[] channels_in_file, int desired_channels) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* channels_in_filePtr = &channels_in_file[0])
				return Native.stbi_loadf_from_file(f, xPtr, yPtr, channels_in_filePtr, desired_channels);
		}
		public static int stbi_is_hdr_from_memory(byte[] buffer, int len) {
			fixed(byte* bufferPtr = &buffer[0])
				return Native.stbi_is_hdr_from_memory(bufferPtr, len);
		}
		public static int stbi_is_hdr(byte[] filename) {
			fixed(byte* filenamePtr = &filename[0])
				return Native.stbi_is_hdr(filenamePtr);
		}
		public static int stbi_info_from_memory(byte[] buffer, int len, int[] x, int[] y, int[] comp) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* compPtr = &comp[0])
				return Native.stbi_info_from_memory(bufferPtr, len, xPtr, yPtr, compPtr);
		}
		public static int stbi_info_from_callbacks(stbi_io_callbacks* clbk, void* user, int[] x, int[] y, int[] comp) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* compPtr = &comp[0])
				return Native.stbi_info_from_callbacks(clbk, user, xPtr, yPtr, compPtr);
		}
		public static int stbi_is_16_bit_from_memory(byte[] buffer, int len) {
			fixed(byte* bufferPtr = &buffer[0])
				return Native.stbi_is_16_bit_from_memory(bufferPtr, len);
		}
		public static int stbi_info(byte[] filename, int[] x, int[] y, int[] comp) {
			fixed(byte* filenamePtr = &filename[0])
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* compPtr = &comp[0])
				return Native.stbi_info(filenamePtr, xPtr, yPtr, compPtr);
		}
		public static int stbi_info_from_file(_IO_FILE* f, int[] x, int[] y, int[] comp) {
			fixed(int* xPtr = &x[0])
			fixed(int* yPtr = &y[0])
			fixed(int* compPtr = &comp[0])
				return Native.stbi_info_from_file(f, xPtr, yPtr, compPtr);
		}
		public static int stbi_is_16_bit(byte[] filename) {
			fixed(byte* filenamePtr = &filename[0])
				return Native.stbi_is_16_bit(filenamePtr);
		}
		public static byte* stbi_zlib_decode_malloc_guesssize(byte[] buffer, int len, int initial_size, int[] outlen) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* outlenPtr = &outlen[0])
				return Native.stbi_zlib_decode_malloc_guesssize(bufferPtr, len, initial_size, outlenPtr);
		}
		public static byte* stbi_zlib_decode_malloc_guesssize_headerflag(byte[] buffer, int len, int initial_size, int[] outlen, int parse_header) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* outlenPtr = &outlen[0])
				return Native.stbi_zlib_decode_malloc_guesssize_headerflag(bufferPtr, len, initial_size, outlenPtr, parse_header);
		}
		public static byte* stbi_zlib_decode_malloc(byte[] buffer, int len, int[] outlen) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* outlenPtr = &outlen[0])
				return Native.stbi_zlib_decode_malloc(bufferPtr, len, outlenPtr);
		}
		public static int stbi_zlib_decode_buffer(byte[] obuffer, int olen, byte[] ibuffer, int ilen) {
			fixed(byte* obufferPtr = &obuffer[0])
			fixed(byte* ibufferPtr = &ibuffer[0])
				return Native.stbi_zlib_decode_buffer(obufferPtr, olen, ibufferPtr, ilen);
		}
		public static byte* stbi_zlib_decode_noheader_malloc(byte[] buffer, int len, int[] outlen) {
			fixed(byte* bufferPtr = &buffer[0])
			fixed(int* outlenPtr = &outlen[0])
				return Native.stbi_zlib_decode_noheader_malloc(bufferPtr, len, outlenPtr);
		}
		public static int stbi_zlib_decode_noheader_buffer(byte[] obuffer, int olen, byte[] ibuffer, int ilen) {
			fixed(byte* obufferPtr = &obuffer[0])
			fixed(byte* ibufferPtr = &ibuffer[0])
				return Native.stbi_zlib_decode_noheader_buffer(obufferPtr, olen, ibufferPtr, ilen);
		}
	}
}
