/**
 *   This file is auto generated by ctocs (c to cs)
 *   https://github.com/apilatosba/ctocs
**/
using System;
using System.Runtime.InteropServices;
using static microui.Native;

namespace microui {
	// DELEGATES
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate int mu_Context_text_width_DELEGATE(void* font, byte* str, int len);
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate int mu_Context_text_height_DELEGATE(void* font);
	[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
	public unsafe delegate void mu_Context_draw_frame_DELEGATE(mu_Context* ctx, mu_Rect rect, int colorid);

	public static unsafe partial class Native {
		public const string LIBRARY_NAME = @"microui.so";

		// DEFINES
		public const string MU_VERSION = "2.02";
		public const int MU_ROOTLIST_SIZE = 32;
		public const int MU_CONTAINERSTACK_SIZE = 32;
		public const int MU_CLIPSTACK_SIZE = 32;
		public const int MU_IDSTACK_SIZE = 32;
		public const int MU_LAYOUTSTACK_SIZE = 16;
		public const int MU_CONTAINERPOOL_SIZE = 48;
		public const int MU_TREENODEPOOL_SIZE = 48;
		public const int MU_MAX_WIDTHS = 16;
		public const string MU_REAL_FMT = "%.3g";
		public const string MU_SLIDER_FMT = "%.2f";
		public const int MU_MAX_FMT = 127;

		// DEFINES THAT ARE WRITTEN IN TERMS OF OTHER DEFINES

		// GLOBAL CONST VARIABLES

		// ENUMS (extracted out)

		// ANONYMOUS ENUMS
		public const int MU_CLIP_PART = 1;
		public const int MU_COMMAND_JUMP = 1;
		public const int MU_COMMAND_CLIP = (MU_COMMAND_JUMP) + 1;
		public const int MU_COMMAND_RECT = (MU_COMMAND_CLIP) + 1;
		public const int MU_COMMAND_TEXT = (MU_COMMAND_RECT) + 1;
		public const int MU_COMMAND_ICON = (MU_COMMAND_TEXT) + 1;
		public const int MU_COLOR_TEXT = 0;
		public const int MU_COLOR_BORDER = (MU_COLOR_TEXT) + 1;
		public const int MU_COLOR_WINDOWBG = (MU_COLOR_BORDER) + 1;
		public const int MU_COLOR_TITLEBG = (MU_COLOR_WINDOWBG) + 1;
		public const int MU_COLOR_TITLETEXT = (MU_COLOR_TITLEBG) + 1;
		public const int MU_COLOR_PANELBG = (MU_COLOR_TITLETEXT) + 1;
		public const int MU_COLOR_BUTTON = (MU_COLOR_PANELBG) + 1;
		public const int MU_COLOR_BUTTONHOVER = (MU_COLOR_BUTTON) + 1;
		public const int MU_COLOR_BUTTONFOCUS = (MU_COLOR_BUTTONHOVER) + 1;
		public const int MU_COLOR_BASE = (MU_COLOR_BUTTONFOCUS) + 1;
		public const int MU_COLOR_BASEHOVER = (MU_COLOR_BASE) + 1;
		public const int MU_COLOR_BASEFOCUS = (MU_COLOR_BASEHOVER) + 1;
		public const int MU_COLOR_SCROLLBASE = (MU_COLOR_BASEFOCUS) + 1;
		public const int MU_COLOR_SCROLLTHUMB = (MU_COLOR_SCROLLBASE) + 1;
		public const int MU_ICON_CLOSE = 1;
		public const int MU_ICON_CHECK = (MU_ICON_CLOSE) + 1;
		public const int MU_ICON_COLLAPSED = (MU_ICON_CHECK) + 1;
		public const int MU_ICON_EXPANDED = (MU_ICON_COLLAPSED) + 1;
		public const int MU_RES_ACTIVE = (1 << 0);
		public const int MU_RES_SUBMIT = (1 << 1);
		public const int MU_OPT_ALIGNCENTER = (1 << 0);
		public const int MU_OPT_ALIGNRIGHT = (1 << 1);
		public const int MU_OPT_NOINTERACT = (1 << 2);
		public const int MU_OPT_NOFRAME = (1 << 3);
		public const int MU_OPT_NORESIZE = (1 << 4);
		public const int MU_OPT_NOSCROLL = (1 << 5);
		public const int MU_OPT_NOCLOSE = (1 << 6);
		public const int MU_OPT_NOTITLE = (1 << 7);
		public const int MU_OPT_HOLDFOCUS = (1 << 8);
		public const int MU_OPT_AUTOSIZE = (1 << 9);
		public const int MU_OPT_POPUP = (1 << 10);
		public const int MU_OPT_CLOSED = (1 << 11);
		public const int MU_MOUSE_LEFT = (1 << 0);
		public const int MU_MOUSE_RIGHT = (1 << 1);
		public const int MU_KEY_SHIFT = (1 << 0);
		public const int MU_KEY_CTRL = (1 << 1);
		public const int MU_KEY_ALT = (1 << 2);
		public const int MU_KEY_BACKSPACE = (1 << 3);

		// FUNCTIONS
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_vec2")]
		public static extern mu_Vec2 mu_vec2(int x, int y);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_rect")]
		public static extern mu_Rect mu_rect(int x, int y, int w, int h);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_color")]
		public static extern mu_Color mu_color(int r, int g, int b, int a);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_init")]
		public static extern void mu_init(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_begin")]
		public static extern void mu_begin(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_end")]
		public static extern void mu_end(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_set_focus")]
		public static extern void mu_set_focus(mu_Context* ctx, uint id);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_get_id")]
		public static extern uint mu_get_id(mu_Context* ctx, void* data, int size);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_push_id")]
		public static extern void mu_push_id(mu_Context* ctx, void* data, int size);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_pop_id")]
		public static extern void mu_pop_id(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_push_clip_rect")]
		public static extern void mu_push_clip_rect(mu_Context* ctx, mu_Rect rect);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_pop_clip_rect")]
		public static extern void mu_pop_clip_rect(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_get_clip_rect")]
		public static extern mu_Rect mu_get_clip_rect(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_check_clip")]
		public static extern int mu_check_clip(mu_Context* ctx, mu_Rect r);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_get_current_container")]
		public static extern mu_Container* mu_get_current_container(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_get_container")]
		public static extern mu_Container* mu_get_container(mu_Context* ctx, byte* name);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_bring_to_front")]
		public static extern void mu_bring_to_front(mu_Context* ctx, mu_Container* cnt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_pool_init")]
		public static extern int mu_pool_init(mu_Context* ctx, mu_PoolItem* items, int len, uint id);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_pool_get")]
		public static extern int mu_pool_get(mu_Context* ctx, mu_PoolItem* items, int len, uint id);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_pool_update")]
		public static extern void mu_pool_update(mu_Context* ctx, mu_PoolItem* items, int idx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_mousemove")]
		public static extern void mu_input_mousemove(mu_Context* ctx, int x, int y);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_mousedown")]
		public static extern void mu_input_mousedown(mu_Context* ctx, int x, int y, int btn);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_mouseup")]
		public static extern void mu_input_mouseup(mu_Context* ctx, int x, int y, int btn);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_scroll")]
		public static extern void mu_input_scroll(mu_Context* ctx, int x, int y);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_keydown")]
		public static extern void mu_input_keydown(mu_Context* ctx, int key);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_keyup")]
		public static extern void mu_input_keyup(mu_Context* ctx, int key);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_input_text")]
		public static extern void mu_input_text(mu_Context* ctx, byte* text);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_push_command")]
		public static extern mu_Command* mu_push_command(mu_Context* ctx, int type, int size);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_next_command")]
		public static extern int mu_next_command(mu_Context* ctx, mu_Command** cmd);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_set_clip")]
		public static extern void mu_set_clip(mu_Context* ctx, mu_Rect rect);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_rect")]
		public static extern void mu_draw_rect(mu_Context* ctx, mu_Rect rect, mu_Color color);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_box")]
		public static extern void mu_draw_box(mu_Context* ctx, mu_Rect rect, mu_Color color);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_text")]
		public static extern void mu_draw_text(mu_Context* ctx, void* font, byte* str, int len, mu_Vec2 pos, mu_Color color);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_icon")]
		public static extern void mu_draw_icon(mu_Context* ctx, int id, mu_Rect rect, mu_Color color);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_row")]
		public static extern void mu_layout_row(mu_Context* ctx, int items, int* widths, int height);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_width")]
		public static extern void mu_layout_width(mu_Context* ctx, int width);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_height")]
		public static extern void mu_layout_height(mu_Context* ctx, int height);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_begin_column")]
		public static extern void mu_layout_begin_column(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_end_column")]
		public static extern void mu_layout_end_column(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_set_next")]
		public static extern void mu_layout_set_next(mu_Context* ctx, mu_Rect r, int relative);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_layout_next")]
		public static extern mu_Rect mu_layout_next(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_control_frame")]
		public static extern void mu_draw_control_frame(mu_Context* ctx, uint id, mu_Rect rect, int colorid, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_draw_control_text")]
		public static extern void mu_draw_control_text(mu_Context* ctx, byte* str, mu_Rect rect, int colorid, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_mouse_over")]
		public static extern int mu_mouse_over(mu_Context* ctx, mu_Rect rect);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_update_control")]
		public static extern void mu_update_control(mu_Context* ctx, uint id, mu_Rect rect, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_text")]
		public static extern void mu_text(mu_Context* ctx, byte* text);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_label")]
		public static extern void mu_label(mu_Context* ctx, byte* text);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_button_ex")]
		public static extern int mu_button_ex(mu_Context* ctx, byte* label, int icon, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_checkbox")]
		public static extern int mu_checkbox(mu_Context* ctx, byte* label, int* state);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_textbox_raw")]
		public static extern int mu_textbox_raw(mu_Context* ctx, byte* buf, int bufsz, uint id, mu_Rect r, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_textbox_ex")]
		public static extern int mu_textbox_ex(mu_Context* ctx, byte* buf, int bufsz, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_slider_ex")]
		public static extern int mu_slider_ex(mu_Context* ctx, float* value, float low, float high, float step, byte* fmt, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_number_ex")]
		public static extern int mu_number_ex(mu_Context* ctx, float* value, float step, byte* fmt, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_header_ex")]
		public static extern int mu_header_ex(mu_Context* ctx, byte* label, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_begin_treenode_ex")]
		public static extern int mu_begin_treenode_ex(mu_Context* ctx, byte* label, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_end_treenode")]
		public static extern void mu_end_treenode(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_begin_window_ex")]
		public static extern int mu_begin_window_ex(mu_Context* ctx, byte* title, mu_Rect rect, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_end_window")]
		public static extern void mu_end_window(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_open_popup")]
		public static extern void mu_open_popup(mu_Context* ctx, byte* name);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_begin_popup")]
		public static extern int mu_begin_popup(mu_Context* ctx, byte* name);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_end_popup")]
		public static extern void mu_end_popup(mu_Context* ctx);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_begin_panel_ex")]
		public static extern void mu_begin_panel_ex(mu_Context* ctx, byte* name, int opt);
		[DllImport(LIBRARY_NAME, CallingConvention = CallingConvention.Cdecl, EntryPoint = "mu_end_panel")]
		public static extern void mu_end_panel(mu_Context* ctx);
	}

	// STRUCTS
	public unsafe partial struct mu_Context {
		public mu_Context_text_width_DELEGATE text_width;
		public mu_Context_text_height_DELEGATE text_height;
		public mu_Context_draw_frame_DELEGATE draw_frame;
		public mu_Style _style;
		public mu_Style* style;
		public uint hover;
		public uint focus;
		public uint last_id;
		public mu_Rect last_rect;
		public int last_zindex;
		public int updated_focus;
		public int frame;
		public mu_Container* hover_root;
		public mu_Container* next_hover_root;
		public mu_Container* scroll_target;
		public fixed byte number_edit_buf[(127)];
		public uint number_edit;
		public mu_Context_command_list_STRUCT command_list;
		public mu_Context_root_list_STRUCT root_list;
		public mu_Context_container_stack_STRUCT container_stack;
		public mu_Context_clip_stack_STRUCT clip_stack;
		public mu_Context_id_stack_STRUCT id_stack;
		public mu_Context_layout_stack_STRUCT layout_stack;
		public mu_Context_container_pool_mu_PoolItem_FIXED_BUFFER container_pool;
		public mu_Context_containers_mu_Container_FIXED_BUFFER containers;
		public mu_Context_treenode_pool_mu_PoolItem_FIXED_BUFFER treenode_pool;
		public mu_Vec2 mouse_pos;
		public mu_Vec2 last_mouse_pos;
		public mu_Vec2 mouse_delta;
		public mu_Vec2 scroll_delta;
		public int mouse_down;
		public int mouse_pressed;
		public int key_down;
		public int key_pressed;
		public fixed byte input_text[(32)];
	}
	public unsafe partial struct mu_Vec2 {
		public int x;
		public int y;
	}
	public unsafe partial struct mu_Rect {
		public int x;
		public int y;
		public int w;
		public int h;
	}
	public unsafe partial struct mu_Color {
		public byte r;
		public byte g;
		public byte b;
		public byte a;
	}
	public unsafe partial struct mu_PoolItem {
		public uint id;
		public int last_update;
	}
	public unsafe partial struct mu_BaseCommand {
		public int type;
		public int size;
	}
	public unsafe partial struct mu_JumpCommand {
		public mu_BaseCommand base_;
		public void* dst;
	}
	public unsafe partial struct mu_ClipCommand {
		public mu_BaseCommand base_;
		public mu_Rect rect;
	}
	public unsafe partial struct mu_RectCommand {
		public mu_BaseCommand base_;
		public mu_Rect rect;
		public mu_Color color;
	}
	public unsafe partial struct mu_TextCommand {
		public mu_BaseCommand base_;
		public void* font;
		public mu_Vec2 pos;
		public mu_Color color;
		public fixed byte str[(1)];
	}
	public unsafe partial struct mu_IconCommand {
		public mu_BaseCommand base_;
		public mu_Rect rect;
		public int id;
		public mu_Color color;
	}
	public unsafe partial struct mu_Layout {
		public mu_Rect body;
		public mu_Rect next;
		public mu_Vec2 position;
		public mu_Vec2 size;
		public mu_Vec2 max;
		public fixed int widths[(16)];
		public int items;
		public int item_index;
		public int next_row;
		public int next_type;
		public int indent;
	}
	public unsafe partial struct mu_Container {
		public mu_Command* head;
		public mu_Command* tail;
		public mu_Rect rect;
		public mu_Rect body;
		public mu_Vec2 content_size;
		public mu_Vec2 scroll;
		public int zindex;
		public int open;
	}
	public unsafe partial struct mu_Style {
		public void* font;
		public mu_Vec2 size;
		public int padding;
		public int spacing;
		public int indent;
		public int title_height;
		public int scrollbar_size;
		public int thumb_size;
		public mu_Style_colors_mu_Color_FIXED_BUFFER colors;
	}
	public unsafe partial struct mu_Context_command_list_STRUCT {
		public int idx;
		public fixed byte items[((256 * 1024))];
	}
	public unsafe partial struct mu_Context_root_list_STRUCT {
		public int idx;
		public mu_Context_root_list_STRUCT_items_mu_Container_FIXED_BUFFER items;
	}
	public unsafe partial struct mu_Context_container_stack_STRUCT {
		public int idx;
		public mu_Context_container_stack_STRUCT_items_mu_Container_FIXED_BUFFER items;
	}
	public unsafe partial struct mu_Context_clip_stack_STRUCT {
		public int idx;
		public mu_Context_clip_stack_STRUCT_items_mu_Rect_FIXED_BUFFER items;
	}
	public unsafe partial struct mu_Context_id_stack_STRUCT {
		public int idx;
		public mu_Context_id_stack_STRUCT_items_mu_Id_FIXED_BUFFER items;
	}
	public unsafe partial struct mu_Context_layout_stack_STRUCT {
		public int idx;
		public mu_Context_layout_stack_STRUCT_items_mu_Layout_FIXED_BUFFER items;
	}

	// OPAQUE STRUCTS

	// UNIONS
	[StructLayout(LayoutKind.Explicit)]
	public unsafe partial struct mu_Command {
		[FieldOffset(0)]
		public int type;
		[FieldOffset(0)]
		public mu_BaseCommand base_;
		[FieldOffset(0)]
		public mu_JumpCommand jump;
		[FieldOffset(0)]
		public mu_ClipCommand clip;
		[FieldOffset(0)]
		public mu_RectCommand rect;
		[FieldOffset(0)]
		public mu_TextCommand text;
		[FieldOffset(0)]
		public mu_IconCommand icon;
	}

	// OPAQUE UNIONS

	// FIXED BUFFER STRUCTS
	public unsafe partial struct mu_Context_container_pool_mu_PoolItem_FIXED_BUFFER {
		public mu_PoolItem e0;
		public mu_PoolItem e1;
		public mu_PoolItem e2;
		public mu_PoolItem e3;
		public mu_PoolItem e4;
		public mu_PoolItem e5;
		public mu_PoolItem e6;
		public mu_PoolItem e7;
		public mu_PoolItem e8;
		public mu_PoolItem e9;
		public mu_PoolItem e10;
		public mu_PoolItem e11;
		public mu_PoolItem e12;
		public mu_PoolItem e13;
		public mu_PoolItem e14;
		public mu_PoolItem e15;
		public mu_PoolItem e16;
		public mu_PoolItem e17;
		public mu_PoolItem e18;
		public mu_PoolItem e19;
		public mu_PoolItem e20;
		public mu_PoolItem e21;
		public mu_PoolItem e22;
		public mu_PoolItem e23;
		public mu_PoolItem e24;
		public mu_PoolItem e25;
		public mu_PoolItem e26;
		public mu_PoolItem e27;
		public mu_PoolItem e28;
		public mu_PoolItem e29;
		public mu_PoolItem e30;
		public mu_PoolItem e31;
		public mu_PoolItem e32;
		public mu_PoolItem e33;
		public mu_PoolItem e34;
		public mu_PoolItem e35;
		public mu_PoolItem e36;
		public mu_PoolItem e37;
		public mu_PoolItem e38;
		public mu_PoolItem e39;
		public mu_PoolItem e40;
		public mu_PoolItem e41;
		public mu_PoolItem e42;
		public mu_PoolItem e43;
		public mu_PoolItem e44;
		public mu_PoolItem e45;
		public mu_PoolItem e46;
		public mu_PoolItem e47;
		public ref mu_PoolItem this[int index] => ref AsSpan()[index];
		public Span<mu_PoolItem> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 48);
	}
	public unsafe partial struct mu_Context_containers_mu_Container_FIXED_BUFFER {
		public mu_Container e0;
		public mu_Container e1;
		public mu_Container e2;
		public mu_Container e3;
		public mu_Container e4;
		public mu_Container e5;
		public mu_Container e6;
		public mu_Container e7;
		public mu_Container e8;
		public mu_Container e9;
		public mu_Container e10;
		public mu_Container e11;
		public mu_Container e12;
		public mu_Container e13;
		public mu_Container e14;
		public mu_Container e15;
		public mu_Container e16;
		public mu_Container e17;
		public mu_Container e18;
		public mu_Container e19;
		public mu_Container e20;
		public mu_Container e21;
		public mu_Container e22;
		public mu_Container e23;
		public mu_Container e24;
		public mu_Container e25;
		public mu_Container e26;
		public mu_Container e27;
		public mu_Container e28;
		public mu_Container e29;
		public mu_Container e30;
		public mu_Container e31;
		public mu_Container e32;
		public mu_Container e33;
		public mu_Container e34;
		public mu_Container e35;
		public mu_Container e36;
		public mu_Container e37;
		public mu_Container e38;
		public mu_Container e39;
		public mu_Container e40;
		public mu_Container e41;
		public mu_Container e42;
		public mu_Container e43;
		public mu_Container e44;
		public mu_Container e45;
		public mu_Container e46;
		public mu_Container e47;
		public ref mu_Container this[int index] => ref AsSpan()[index];
		public Span<mu_Container> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 48);
	}
	public unsafe partial struct mu_Context_treenode_pool_mu_PoolItem_FIXED_BUFFER {
		public mu_PoolItem e0;
		public mu_PoolItem e1;
		public mu_PoolItem e2;
		public mu_PoolItem e3;
		public mu_PoolItem e4;
		public mu_PoolItem e5;
		public mu_PoolItem e6;
		public mu_PoolItem e7;
		public mu_PoolItem e8;
		public mu_PoolItem e9;
		public mu_PoolItem e10;
		public mu_PoolItem e11;
		public mu_PoolItem e12;
		public mu_PoolItem e13;
		public mu_PoolItem e14;
		public mu_PoolItem e15;
		public mu_PoolItem e16;
		public mu_PoolItem e17;
		public mu_PoolItem e18;
		public mu_PoolItem e19;
		public mu_PoolItem e20;
		public mu_PoolItem e21;
		public mu_PoolItem e22;
		public mu_PoolItem e23;
		public mu_PoolItem e24;
		public mu_PoolItem e25;
		public mu_PoolItem e26;
		public mu_PoolItem e27;
		public mu_PoolItem e28;
		public mu_PoolItem e29;
		public mu_PoolItem e30;
		public mu_PoolItem e31;
		public mu_PoolItem e32;
		public mu_PoolItem e33;
		public mu_PoolItem e34;
		public mu_PoolItem e35;
		public mu_PoolItem e36;
		public mu_PoolItem e37;
		public mu_PoolItem e38;
		public mu_PoolItem e39;
		public mu_PoolItem e40;
		public mu_PoolItem e41;
		public mu_PoolItem e42;
		public mu_PoolItem e43;
		public mu_PoolItem e44;
		public mu_PoolItem e45;
		public mu_PoolItem e46;
		public mu_PoolItem e47;
		public ref mu_PoolItem this[int index] => ref AsSpan()[index];
		public Span<mu_PoolItem> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 48);
	}
	public unsafe partial struct mu_Style_colors_mu_Color_FIXED_BUFFER {
		public ref mu_Color this[int index] => ref AsSpan()[index];
		public Span<mu_Color> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 0);
	}
	public unsafe partial struct mu_Context_root_list_STRUCT_items_mu_Container_FIXED_BUFFER {
		public mu_Container* e0;
		public mu_Container* e1;
		public mu_Container* e2;
		public mu_Container* e3;
		public mu_Container* e4;
		public mu_Container* e5;
		public mu_Container* e6;
		public mu_Container* e7;
		public mu_Container* e8;
		public mu_Container* e9;
		public mu_Container* e10;
		public mu_Container* e11;
		public mu_Container* e12;
		public mu_Container* e13;
		public mu_Container* e14;
		public mu_Container* e15;
		public mu_Container* e16;
		public mu_Container* e17;
		public mu_Container* e18;
		public mu_Container* e19;
		public mu_Container* e20;
		public mu_Container* e21;
		public mu_Container* e22;
		public mu_Container* e23;
		public mu_Container* e24;
		public mu_Container* e25;
		public mu_Container* e26;
		public mu_Container* e27;
		public mu_Container* e28;
		public mu_Container* e29;
		public mu_Container* e30;
		public mu_Container* e31;
		public ref mu_Container* this[int index] { get { fixed (mu_Container** ptr = &e0) { return ref ptr[index]; } } }
	}
	public unsafe partial struct mu_Context_container_stack_STRUCT_items_mu_Container_FIXED_BUFFER {
		public mu_Container* e0;
		public mu_Container* e1;
		public mu_Container* e2;
		public mu_Container* e3;
		public mu_Container* e4;
		public mu_Container* e5;
		public mu_Container* e6;
		public mu_Container* e7;
		public mu_Container* e8;
		public mu_Container* e9;
		public mu_Container* e10;
		public mu_Container* e11;
		public mu_Container* e12;
		public mu_Container* e13;
		public mu_Container* e14;
		public mu_Container* e15;
		public mu_Container* e16;
		public mu_Container* e17;
		public mu_Container* e18;
		public mu_Container* e19;
		public mu_Container* e20;
		public mu_Container* e21;
		public mu_Container* e22;
		public mu_Container* e23;
		public mu_Container* e24;
		public mu_Container* e25;
		public mu_Container* e26;
		public mu_Container* e27;
		public mu_Container* e28;
		public mu_Container* e29;
		public mu_Container* e30;
		public mu_Container* e31;
		public ref mu_Container* this[int index] { get { fixed (mu_Container** ptr = &e0) { return ref ptr[index]; } } }
	}
	public unsafe partial struct mu_Context_clip_stack_STRUCT_items_mu_Rect_FIXED_BUFFER {
		public mu_Rect e0;
		public mu_Rect e1;
		public mu_Rect e2;
		public mu_Rect e3;
		public mu_Rect e4;
		public mu_Rect e5;
		public mu_Rect e6;
		public mu_Rect e7;
		public mu_Rect e8;
		public mu_Rect e9;
		public mu_Rect e10;
		public mu_Rect e11;
		public mu_Rect e12;
		public mu_Rect e13;
		public mu_Rect e14;
		public mu_Rect e15;
		public mu_Rect e16;
		public mu_Rect e17;
		public mu_Rect e18;
		public mu_Rect e19;
		public mu_Rect e20;
		public mu_Rect e21;
		public mu_Rect e22;
		public mu_Rect e23;
		public mu_Rect e24;
		public mu_Rect e25;
		public mu_Rect e26;
		public mu_Rect e27;
		public mu_Rect e28;
		public mu_Rect e29;
		public mu_Rect e30;
		public mu_Rect e31;
		public ref mu_Rect this[int index] => ref AsSpan()[index];
		public Span<mu_Rect> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 32);
	}
	public unsafe partial struct mu_Context_id_stack_STRUCT_items_mu_Id_FIXED_BUFFER {
		public uint e0;
		public uint e1;
		public uint e2;
		public uint e3;
		public uint e4;
		public uint e5;
		public uint e6;
		public uint e7;
		public uint e8;
		public uint e9;
		public uint e10;
		public uint e11;
		public uint e12;
		public uint e13;
		public uint e14;
		public uint e15;
		public uint e16;
		public uint e17;
		public uint e18;
		public uint e19;
		public uint e20;
		public uint e21;
		public uint e22;
		public uint e23;
		public uint e24;
		public uint e25;
		public uint e26;
		public uint e27;
		public uint e28;
		public uint e29;
		public uint e30;
		public uint e31;
		public ref uint this[int index] => ref AsSpan()[index];
		public Span<uint> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 32);
	}
	public unsafe partial struct mu_Context_layout_stack_STRUCT_items_mu_Layout_FIXED_BUFFER {
		public mu_Layout e0;
		public mu_Layout e1;
		public mu_Layout e2;
		public mu_Layout e3;
		public mu_Layout e4;
		public mu_Layout e5;
		public mu_Layout e6;
		public mu_Layout e7;
		public mu_Layout e8;
		public mu_Layout e9;
		public mu_Layout e10;
		public mu_Layout e11;
		public mu_Layout e12;
		public mu_Layout e13;
		public mu_Layout e14;
		public mu_Layout e15;
		public ref mu_Layout this[int index] => ref AsSpan()[index];
		public Span<mu_Layout> AsSpan() => MemoryMarshal.CreateSpan(ref e0, 16);
	}

	// ENUMS

	// OPAQUE ENUMS

	// SAFE WRAPPER
	/**
	 *    The functions here may not always work depending on how the function uses the pointer
	 *    You should know when to use these functions instead of the functions in Native
	**/
	public static unsafe partial class Safe {
		public static mu_Container* mu_get_container(mu_Context* ctx, byte[] name) {
			fixed(byte* namePtr = &name[0])
				return Native.mu_get_container(ctx, namePtr);
		}
		public static void mu_input_text(mu_Context* ctx, byte[] text) {
			fixed(byte* textPtr = &text[0])
				Native.mu_input_text(ctx, textPtr);
		}
		public static void mu_draw_text(mu_Context* ctx, void* font, byte[] str, int len, mu_Vec2 pos, mu_Color color) {
			fixed(byte* strPtr = &str[0])
				Native.mu_draw_text(ctx, font, strPtr, len, pos, color);
		}
		public static void mu_layout_row(mu_Context* ctx, int items, int[] widths, int height) {
			fixed(int* widthsPtr = &widths[0])
				Native.mu_layout_row(ctx, items, widthsPtr, height);
		}
		public static void mu_draw_control_text(mu_Context* ctx, byte[] str, mu_Rect rect, int colorid, int opt) {
			fixed(byte* strPtr = &str[0])
				Native.mu_draw_control_text(ctx, strPtr, rect, colorid, opt);
		}
		public static void mu_text(mu_Context* ctx, byte[] text) {
			fixed(byte* textPtr = &text[0])
				Native.mu_text(ctx, textPtr);
		}
		public static void mu_label(mu_Context* ctx, byte[] text) {
			fixed(byte* textPtr = &text[0])
				Native.mu_label(ctx, textPtr);
		}
		public static int mu_button_ex(mu_Context* ctx, byte[] label, int icon, int opt) {
			fixed(byte* labelPtr = &label[0])
				return Native.mu_button_ex(ctx, labelPtr, icon, opt);
		}
		public static int mu_checkbox(mu_Context* ctx, byte[] label, int[] state) {
			fixed(byte* labelPtr = &label[0])
			fixed(int* statePtr = &state[0])
				return Native.mu_checkbox(ctx, labelPtr, statePtr);
		}
		public static int mu_textbox_raw(mu_Context* ctx, byte[] buf, int bufsz, uint id, mu_Rect r, int opt) {
			fixed(byte* bufPtr = &buf[0])
				return Native.mu_textbox_raw(ctx, bufPtr, bufsz, id, r, opt);
		}
		public static int mu_textbox_ex(mu_Context* ctx, byte[] buf, int bufsz, int opt) {
			fixed(byte* bufPtr = &buf[0])
				return Native.mu_textbox_ex(ctx, bufPtr, bufsz, opt);
		}
		public static int mu_slider_ex(mu_Context* ctx, float[] value, float low, float high, float step, byte[] fmt, int opt) {
			fixed(float* valuePtr = &value[0])
			fixed(byte* fmtPtr = &fmt[0])
				return Native.mu_slider_ex(ctx, valuePtr, low, high, step, fmtPtr, opt);
		}
		public static int mu_number_ex(mu_Context* ctx, float[] value, float step, byte[] fmt, int opt) {
			fixed(float* valuePtr = &value[0])
			fixed(byte* fmtPtr = &fmt[0])
				return Native.mu_number_ex(ctx, valuePtr, step, fmtPtr, opt);
		}
		public static int mu_header_ex(mu_Context* ctx, byte[] label, int opt) {
			fixed(byte* labelPtr = &label[0])
				return Native.mu_header_ex(ctx, labelPtr, opt);
		}
		public static int mu_begin_treenode_ex(mu_Context* ctx, byte[] label, int opt) {
			fixed(byte* labelPtr = &label[0])
				return Native.mu_begin_treenode_ex(ctx, labelPtr, opt);
		}
		public static int mu_begin_window_ex(mu_Context* ctx, byte[] title, mu_Rect rect, int opt) {
			fixed(byte* titlePtr = &title[0])
				return Native.mu_begin_window_ex(ctx, titlePtr, rect, opt);
		}
		public static void mu_open_popup(mu_Context* ctx, byte[] name) {
			fixed(byte* namePtr = &name[0])
				Native.mu_open_popup(ctx, namePtr);
		}
		public static int mu_begin_popup(mu_Context* ctx, byte[] name) {
			fixed(byte* namePtr = &name[0])
				return Native.mu_begin_popup(ctx, namePtr);
		}
		public static void mu_begin_panel_ex(mu_Context* ctx, byte[] name, int opt) {
			fixed(byte* namePtr = &name[0])
				Native.mu_begin_panel_ex(ctx, namePtr, opt);
		}
	}
}
